version: '3.8'

services:
  chimera-trading-system:
    build:
      context: .
      dockerfile: Dockerfile.unified
    container_name: chimera-trading-system
    ports:
      - "80:80"           # Web dashboard
      - "5900:5900"       # VNC access to IBKR Gateway GUI
      - "4002:4002"       # IBKR Gateway API (paper trading)
    environment:
      # IBKR Gateway Configuration
      - DATA_SOURCE=ibkr
      - IBKR_HOST=127.0.0.1
      - IBKR_PORT=4002
      - IBKR_CLIENT_ID=1
      - IBKR_READONLY=false
      
      # IBKR Credentials
      - TWS_USERID=isht1430
      - TWS_PASSWORD=Gamma@1430Nav9464
      - TRADING_MODE=paper
      - ACCOUNT_CODE=DU2838017
      
      # Trading Configuration
      - TRADING_SYMBOLS=AAPL,MSFT,GOOGL,AMZN,TSLA,NVDA,META,SPY,QQQ
      - MAX_POSITION_SIZE=1000
      - MAX_PORTFOLIO_RISK=0.02
      - STOP_LOSS_PCT=0.015
      - TAKE_PROFIT_RATIO=2.0
      
      # System Configuration
      - LOG_LEVEL=INFO
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - FRONTEND_PORT=80
      
      # Display for IBKR Gateway
      - DISPLAY=:99
    volumes:
      - chimera_data:/app/chimera/data
      - chimera_logs:/app/chimera/logs
      - chimera_config:/app/chimera/config
    networks:
      - chimera-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  chimera_data:
    driver: local
  chimera_logs:
    driver: local
  chimera_config:
    driver: local

networks:
  chimera-network:
    driver: bridge

